name: "Eureka DevSecops"
description: "Scan your code with Eureka DevSecOps to discover potential security risks and vulnerabilities"

inputs:
  args:
    description: "Additional Eureka DevSecOps CLI arguments"
    required: false
  eureka_registry_url:
    description: "Eureka container registry URL"
    required: false
    default: "eurekahubprodagentacr.azurecr.io"
  eureka_repo:
    description: "Eureka repository name"
    required: false
    default: "fwdsec/eureka"
  eureka_tag:
    description: "Eureka container tag"
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Login to the Docker Registry
      shell: bash
      run: |
        docker login -u ${EUREKA_USER} -p ${EUREKA_PASSWORD} ${{ inputs.eureka_registry_url }}

    - name: Pull down Eureka container
      shell: bash
      run: |
        docker pull ${{ inputs.eureka_registry_url }}/${{ inputs.eureka_repo }}:${{ inputs.eureka_tag }}

    - name: Run Eureka scan
      shell: bash
      run: |
        docker run --rm --network host \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v "$(pwd)":/home/repo \
          -e DIND_USER_HOME="$(pwd)" \
          -e EUREKA_ENDPOINT="${EUREKA_ENDPOINT}" \
          -e EUREKA_USER="${EUREKA_USER}" \
          -e EUREKA_PASSWORD="${EUREKA_PASSWORD}" \
          -e PROFILE_INFO="${PROFILE_INFO}" \
          ${{ inputs.eureka_registry_url }}/${{ inputs.eureka_repo }}:${{ inputs.eureka_tag }}
