name: "Eureka DevSecops"
description: "Scan your code with Eureka DevSecOps to discover potential security risks and vulnerabilities"
inputs:
  args:
    description: "Additional Eureka DevSecOps CLI arguments"
    required: false
  pr_report:
    description: "Enable a Eureka scan report as a comment in the pull request"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Login to the Docker Registry
      shell: bash
      run: |
        docker login -u ${EUREKA_USER} -p ${EUREKA_PASSWORD} ${EUREKA_REGISTRY_URL}

    - name: Preparing summary report
      shell: bash
      id: report_prep
      if: inputs.pr_report == 'true'
      run: |
        TMPDIR=$(mktemp -d)
        echo "Eureka scan did not complete!" > $TMPDIR/summary.log
        echo "report_file=$TMPDIR/summary.log" >> "$GITHUB_OUTPUT"        
        echo "tmpdir=$TMPDIR" >> "$GITHUB_OUTPUT"
    
    - name: Pull down Eureka container
      shell: bash
      run: |
        docker pull ${EUREKA_REGISTRY_URL}/${EUREKA_REPO}:${EUREKA_TAG}

    - name: Run Eureka scan
      shell: bash
      run: |
        docker run --rm --network host \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v "$(pwd)":/home/repo \
          -e DIND_USER_HOME="$(pwd)" \
          -v "${{ steps.report_prep.outputs.tmpdir }}:/tmp/eureka" \
          -e EUREKA_OUTPUT=/tmp/eureka/summary.log \
          -e EUREKA_ENDPOINT="${EUREKA_ENDPOINT}" \
          -e EUREKA_USER="${EUREKA_USER}" \
          -e EUREKA_PASSWORD="${EUREKA_PASSWORD}" \
          -e PROFILE_INFO="${PROFILE_INFO}" \
          ${EUREKA_REGISTRY_URL}/${EUREKA_REPO}:${EUREKA_TAG} 

    - name: Write Eureka report to comment
      if: inputs.pr_report == 'true'
      uses: mshick/add-pr-comment@v2
      with:
        message-path: ${{ steps.report_prep.outputs.report_file }}