name: "Eureka DevSecOps"
description: "Scan your code with Eureka DevSecOps to discover potential security risks and vulnerabilities"
runs:
  using: "composite"
  steps:
    - name: Login to the Docker Registry
      shell: bash
      run: |
        docker login -u ${EUREKA_USER} -p ${EUREKA_PASSWORD} eurekahubprodagentacr.azurecr.io

    - name: Pull down Eureka container
      shell: bash
      run: |
        docker pull eurekahubprodagentacr.azurecr.io/fwdsec/eureka:latest

    - name: Run Eureka scan
      shell: bash
      run: |
        docker run --rm --network host \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v "$(pwd)":/home/repo \
          -e DIND_USER_HOME="$(pwd)" \
          -e EUREKA_ENDPOINT="${EUREKA_ENDPOINT}" \
          -e EUREKA_USER="${EUREKA_USER}" \
          -e EUREKA_PASSWORD="${EUREKA_PASSWORD}" \
          -e PROFILE_INFO="${PROFILE_INFO}" \
          eurekahubprodagentacr.azurecr.io/fwdsec/eureka:latest
