name: Smoke Test

on:
  push:
    branches:
      - "main"

jobs:
  eureka-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Scan
        uses: EurekaDevSecOps/scan-action@main
        with:
          scanners: gitleaks,opengrep,grype
